#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod console;
pub mod console_2;
pub mod context;
pub mod contract_test;
pub mod ds_test;
pub mod erc20;
pub mod erc721;
pub mod erc721_token_receiver;
pub mod i_land_bank;
pub mod i_land_nft;
pub mod i_swap_token;
pub mod i_uniswap_v2_factory;
pub mod i_uniswap_v2_pair;
pub mod i_uniswap_v2_router;
pub mod ierc165;
pub mod ierc20;
pub mod ierc721;
pub mod land_bank;
pub mod land_nft;
pub mod marketplace;
pub mod ownable;
pub mod pausable;
pub mod reentrancy_guard;
pub mod safe_transfer_lib;
pub mod script;
pub mod std_error;
pub mod std_math;
pub mod std_storage;
pub mod strings;
pub mod swap_token;
pub mod test;
pub mod vm;
